[theme]
base = "light"
primaryColor = "#2b3928"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#ffffff"
textColor = "#000000"
font = "sans serif"

[server]
maxUploadSize = 20
fileWatcherType = "none"

[browser]
gatherUsageStats = false
